import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const worker=read('src/worker.js'),html=read('public/index.html'),css=read('public/styles.css'),schema=read('schema.sql'),pkg=JSON.parse(read('package.json')),seed=JSON.parse(read('data/source-registry.seed.json')),stats=fs.existsSync('data/registry-stats.json')?JSON.parse(read('data/registry-stats.json')):{certifiedUniqueHosts:seed.length,certifiedSources:seed.length};
const fail=m=>{throw new Error(m)};
if(/openai|anthropic|gemini|flootAi|workers-ai|ai gateway/i.test(worker))fail('Runtime LLM dependency detected');
if(/\b(?:serpapi|tavily|firecrawl|tinyfish)\b|bing\s+search|google\s+custom\s+search|\bexa(?:\.ai)?\b/i.test(worker))fail('External search API/runtime dependency detected');
if(!worker.includes('robotsAllowedForUrl'))fail('Path-level robots gate missing');
if(!worker.includes('safePublicUrl'))fail('SSRF guard missing');
if(!worker.includes('const BATCH_SOURCE_IDS = 1'))fail('Free-tier source isolation missing');
if(!worker.includes('QUEUE_BATCH_MESSAGES = 100'))fail('Queue producer batching missing');
if(!worker.includes('sendBatch'))fail('Large-scan queue batching missing');
if(!worker.includes('local_corpus_lexical_match'))fail('Local corpus retrieval missing');
if(!worker.includes('const MIN_EXPERT_DOCUMENTS = 1000'))fail('Expert documentary corpus floor missing');
if(!schema.includes('CREATE TABLE IF NOT EXISTS documents'))fail('Document corpus table missing');
if(!schema.includes('CREATE TABLE IF NOT EXISTS job_documents'))fail('Per-job corpus mapping missing');
if(!schema.includes('CREATE TABLE IF NOT EXISTS job_source_status'))fail('Queue idempotency table missing');
if(!schema.includes('CREATE TABLE IF NOT EXISTS document_search'))fail('Deterministic local document index missing');
if(!schema.includes("verification_level IN ('V2','V3')"))fail('V2/V3 Corpus A gate missing');
if(!schema.includes("corpus!='A'")&&!schema.includes("corpus != 'A'"))fail('Corpus A integrity constraint missing');
if(!schema.includes('official = 1 AND public_access = 1 AND free_access = 1'))fail('3/3 source gate missing');
if(seed.some(x=>!(x.official&&x.public_access&&x.free_access&&x.active)))fail('Invalid active seed source');
if(!html.includes('LEYTON<span>•</span>FRANCE'))fail('Leyton France identity missing');
if(!css.includes('grid-template-columns:340px minmax(0,1fr)'))fail('13-inch two-column layout missing');
if(!css.includes('overflow-x:hidden'))fail('Horizontal overflow guard missing');
if(/fonts\.googleapis\.com|@import\s+url\(/i.test(css))fail('External font dependency detected');
if(pkg.name!=='artscan-rd')fail('Package identity invalid');
console.log(JSON.stringify({ok:true,llmRuntime:false,externalSearchApiRuntime:false,robotsPathRules:true,ssrf:true,sourceGate:'3/3',batchSourceIds:1,registrySeedCount:seed.length,certifiedSources:Number(stats.certifiedSources||seed.length),certifiedUniqueHosts:Number(stats.certifiedUniqueHosts||seed.length),institutionalRegistryHosts:Number(stats.certifiedUniqueHosts||seed.length),desktopTarget:'1366x768'},null,2));
