import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const worker=read('src/worker.js'),app=read('public/app.js'),html=read('public/index.html'),css=read('public/styles.css'),schema=read('schema.sql'),pkg=JSON.parse(read('package.json')),seed=JSON.parse(read('data/source-registry.seed.json')),stats=fs.existsSync('data/registry-stats.json')?JSON.parse(read('data/registry-stats.json')):{certifiedUniqueHosts:seed.length,certifiedSources:seed.length},qualityWorkflow=read('.github/workflows/quality.yml'),registryWorkflow=read('.github/workflows/registry-certification.yml'),stagingDeploy=read('.github/workflows/deploy-cloudflare-staging.yml'),productionDeploy=read('.github/workflows/deploy-cloudflare.yml'),corpusHarvestWorkflow=read('.github/workflows/corpus-a-harvest.yml'),rebuildWorkflow=read('.github/workflows/rebuild-registry-artifacts.yml'),harvestScript=read('scripts/harvest-corpus-a.mjs');
const fail=m=>{throw new Error(m)};
const buildScript=read('scripts/build-registry.mjs'),seedCertScript=read('scripts/certify-seed-sources.mjs'),authoritativeCertScript=read('scripts/certify-authoritative-directories.mjs'),generatedRegistry=JSON.parse(read('data/source-registry.generated.json')),generatedCorpus=JSON.parse(read('data/corpus-a.generated.json'));
const corpusStats=JSON.parse(read('data/corpus-a-stats.json'));
const corpusAccessRoots=new Set(generatedCorpus.filter(d=>d?.corpus==='A'&&d?.active===true&&d?.official===true&&d?.public_access===true&&d?.free_access===true&&d?.primary_secondary==='primary'&&d?.access_status==='free'&&['V2','V3'].includes(d?.verification_level)&&Number(d?.http_status)>=200&&Number(d?.http_status)<300).map(d=>d.source_root_url));
const hasRecorded2xx=x=>{const raw=x?.access_http_status??x?.last_http_status;if(raw==null)return false;const n=Number(raw);return Number.isFinite(n)&&n>=200&&n<300};
if(/openai|anthropic|gemini|flootAi|workers-ai|ai gateway/i.test(worker))fail('Runtime LLM dependency detected');
if(/\b(?:serpapi|tavily|firecrawl|tinyfish)\b|bing\s+search|google\s+custom\s+search|\bexa(?:\.ai)?\b/i.test(worker))fail('External search API/runtime dependency detected');
if(!worker.includes('robotsAllowedForUrl'))fail('Path-level robots gate missing');
if(!worker.includes('safePublicUrl'))fail('SSRF guard missing');
if(!worker.includes('const BATCH_SOURCE_IDS = 1'))fail('Free-tier source isolation missing');
if(!worker.includes('QUEUE_BATCH_MESSAGES = 100'))fail('Queue producer batching missing');
if(!worker.includes('sendBatch'))fail('Large-scan queue batching missing');
if(!worker.includes('local_corpus_lexical_match'))fail('Local corpus retrieval missing');
if(!worker.includes('const MIN_EXPERT_DOCUMENTS = 1000'))fail('Expert documentary corpus floor missing');
if(!worker.includes('const MIN_EXPERT_SOURCES = 1000'))fail('Expert institutional-source floor missing');
if(!worker.includes('corpusASources'))fail('Corpus A represented-source metric missing');
if(!worker.includes('selectedDocuments'))fail('Per-research documentary selection metric missing');
if(!worker.includes('corpusVerified'))fail('Global Corpus A metric missing');
if(!worker.includes('corpusComplete'))fail('Global Corpus A readiness metric missing');
if(!worker.includes('corpus_relevance'))fail('Corpus-ranked source selection missing');
if(!worker.includes('depth==="expert"&&!n.productionReady'))fail('Expert mode production-readiness gate missing');
if(!app.includes('expert.disabled=!ready'))fail('Expert UI readiness gate missing');
if(/sources effectivement validées/i.test(app))fail('Per-research documents are mislabeled as sources');
if(!qualityWorkflow.includes('workflow_dispatch:'))fail('Manual quality verification missing');
if(!registryWorkflow.includes('cron: "0 0,1 1,15 * *"')||!registryWorkflow.includes('TZ=Europe/Paris'))fail('Fortnightly 02:00 Europe/Paris registry schedule missing');
if(!registryWorkflow.includes("github.event_name == 'schedule'")||!registryWorkflow.includes('d1 execute artscan-rd --remote')||!registryWorkflow.includes('Production Corpus A mismatch'))fail('Validated scheduled production data promotion missing');
if(!harvestScript.includes("UPDATE documents SET active=0, updated_at=CURRENT_TIMESTAMP WHERE corpus='A' AND active=1"))fail('Corpus A stale-document deactivation missing from generator');
if(!harvestScript.includes('MAX_DOCS_PER_SOURCE=1')||!harvestScript.includes('TARGET_DOCS=1000')||!harvestScript.includes('TARGET_SOURCES=1000')||!harvestScript.includes('sources_represented:sourcesRepresented')||!harvestScript.includes('sourcesRepresented>=TARGET_SOURCES'))fail('Broad institutional Corpus A coverage logic missing');
if(!harvestScript.includes('rootDocumentScore')||!harvestScript.includes('if(rootScore>=4)c.set(resolved,rootScore)'))fail('Substantive institutional root-document fallback missing');
for(const [name,w] of [['registry',registryWorkflow],['staging deploy',stagingDeploy],['production deploy',productionDeploy],['corpus harvest',corpusHarvestWorkflow],['registry rebuild',rebuildWorkflow]])if(!w.includes("UPDATE documents SET active=0, updated_at=CURRENT_TIMESTAMP WHERE corpus='A' AND active=1"))fail(name+' stale Corpus A cleanup missing');
if(!stagingDeploy.includes('workflow_dispatch:')||/^\s*push:/m.test(stagingDeploy)||/^\s*schedule:/m.test(stagingDeploy))fail('Staging deploy must remain manual-only');
if(!productionDeploy.includes('workflow_dispatch:')||/^\s*push:/m.test(productionDeploy)||/^\s*schedule:/m.test(productionDeploy))fail('Production deploy must remain manual-only');
if(!seedCertScript.includes('anonymous_direct_http_2xx')||!seedCertScript.includes('verified_corpus_a_http_2xx'))fail('Seed direct/documentary access recertification missing');
if(!authoritativeCertScript.includes('embeddedUrls')||!authoritativeCertScript.includes('for(let attempt=0;attempt<3&&!page;attempt++)'))fail('Authoritative directory resilience missing');
if(!authoritativeCertScript.includes('snapshotFresh')||!authoritativeCertScript.includes('authoritative_directory_snapshot_fallback_plus_current_anonymous_http_access'))fail('Time-bounded official-directory fallback integrity missing');
if(!authoritativeCertScript.includes('National Cancer Institute (NCI)')||!authoritativeCertScript.includes('National Center for Complementary and Integrative Health (NCCIH)'))fail('NIH official IC fallback coverage missing');
if(!buildScript.includes('excludedWithoutAccessEvidence')||buildScript.includes('access_checked_at||new Date'))fail('Registry access-evidence gate or truthful timestamp handling missing');
if(generatedRegistry.some(x=>!(x?.official===true&&x?.public_access===true&&x?.free_access===true&&x?.active===true)))fail('Invalid generated 3/3 source');
if(new Set(generatedRegistry.map(x=>x.root_url)).size!==generatedRegistry.length)fail('Duplicate generated registry root URL');
if(generatedRegistry.some(x=>!hasRecorded2xx(x)&&!corpusAccessRoots.has(x.root_url)))fail('Generated source without direct or documentary access evidence');
if(Number(stats.certifiedSources||0)!==generatedRegistry.length)fail('Registry stats/source count mismatch');
if(generatedCorpus.some(x=>x?.corpus!=='A'||x?.official!==true||x?.public_access!==true||x?.free_access!==true||x?.primary_secondary!=='primary'||x?.access_status!=='free'||!['V2','V3'].includes(x?.verification_level)))fail('Invalid generated Corpus A document');
if(new Set(generatedCorpus.map(x=>x.canonical_hash)).size!==generatedCorpus.length)fail('Duplicate Corpus A canonical hash');
if(new Set(generatedCorpus.map(x=>x.canonical_url)).size!==generatedCorpus.length)fail('Duplicate Corpus A canonical URL');
if(corpusStats.complete===true&&(Number(corpusStats.verified_unique_documents||0)<Number(corpusStats.target||1000)||Number(corpusStats.sources_represented||0)<Number(corpusStats.target_sources||1000)))fail('Corpus A falsely marked complete');
const generatedRoots=new Set(generatedRegistry.map(x=>x.root_url));
if(generatedCorpus.some(x=>!generatedRoots.has(x.source_root_url)))fail('Corpus A document orphaned from certified registry');
if(!schema.includes('CREATE TABLE IF NOT EXISTS documents'))fail('Document corpus table missing');
if(!schema.includes('CREATE TABLE IF NOT EXISTS job_documents'))fail('Per-job corpus mapping missing');
if(!schema.includes('CREATE TABLE IF NOT EXISTS job_source_status'))fail('Queue idempotency table missing');
if(!schema.includes('CREATE TABLE IF NOT EXISTS document_search'))fail('Deterministic local document index missing');
if(!schema.includes("verification_level IN ('V2','V3')"))fail('V2/V3 Corpus A gate missing');
if(!schema.includes("corpus!='A'")&&!schema.includes("corpus != 'A'"))fail('Corpus A integrity constraint missing');
if(!schema.includes('official = 1 AND public_access = 1 AND free_access = 1'))fail('3/3 source gate missing');
if(seed.some(x=>!(x.official&&x.public_access&&x.free_access&&x.active)))fail('Invalid active seed source');
if(!html.includes('LEYTON<span>•</span>FRANCE'))fail('Leyton France identity missing');
if(!css.includes('grid-template-columns:340px minmax(0,1fr)'))fail('13-inch two-column layout missing');
if(!css.includes('overflow-x:hidden'))fail('Horizontal overflow guard missing');
if(/fonts\.googleapis\.com|@import\s+url\(/i.test(css))fail('External font dependency detected');
if(!css.trimStart().startsWith(':root{'))fail('Malformed CSS prefix residue detected');
if(pkg.name!=='artscan-rd')fail('Package identity invalid');
console.log(JSON.stringify({ok:true,llmRuntime:false,externalSearchApiRuntime:false,robotsPathRules:true,ssrf:true,sourceGate:'3/3',batchSourceIds:1,registrySeedCount:seed.length,certifiedSources:Number(stats.certifiedSources||seed.length),certifiedUniqueHosts:Number(stats.certifiedUniqueHosts||seed.length),institutionalRegistryHosts:Number(stats.certifiedUniqueHosts||seed.length),desktopTarget:'1366x768'},null,2));
